### PR TITLE
Added Delete Button to Map View Controls

### PR DESCRIPTION
**Pull request by astraiophos**
The current delete button is limited to delete only features on vector layers. I have also edited the css file and added a new icon to the existing list following the same style as previous icons. Feel free to ask me any questions

### CODE REVIEW

**Comment by swainn** [comment]
Finally got some time to look at this. Unfortunately, you have made your changes on the master branch. All new features need to be done on the dev branch. To switch to your dev branch change into your tethys src directory and run:

$ git checkout dev

Make the same changes on the dev branch, confirm they still work, and submit a new pull request.

Also, this needs to be documented better, but the CSS files in Tethys are generated from LESS files (you'll find in a less directory). You need to make the changes in the LESS file, and use their commandline utility to generate the CSS. Otherwise, next time the CSS is generated, your changes will be overwritten.

**Comment by astraiophos** [comment]
What about the icons? Do I need to update anything besides the existing icon file? I just got in and I'm working in the changes like you mentioned, still haven't gotten to the LESS stuff yet
On Jul 21, 2016 10:45 AM, Nathan Swain <notifications@github.com> wrote:Finally got some time to look at this. Unfortunately, you have made your changes on the master branch. All new features need to be done on the dev branch. To switch to your dev branch change into your tethys src directory and run:

$ git checkout dev

Make the same changes on the dev branch, confirm they still work, and submit a new pull request.

Also, this needs to be documented better, but the CSS files in Tethys are generated from LESS files (you'll find in a less directory). You need to make the changes in the LESS file, and use their commandline utility to generate the CSS. Otherwise, next time the CSS is generated, your changes will be overwritten.

**Comment by astraiophos** [comment]
One last question, I can add the bootstraps tooltip stuff while I'm at this, shall I do that or do a different pull request?
On Jul 21, 2016 10:45 AM, Nathan Swain <notifications@github.com> wrote:Finally got some time to look at this. Unfortunately, you have made your changes on the master branch. All new features need to be done on the dev branch. To switch to your dev branch change into your tethys src directory and run:

$ git checkout dev

Make the same changes on the dev branch, confirm they still work, and submit a new pull request.

Also, this needs to be documented better, but the CSS files in Tethys are generated from LESS files (you'll find in a less directory). You need to make the changes in the LESS file, and use their commandline utility to generate the CSS. Otherwise, next time the CSS is generated, your changes will be overwritten.

**Comment by swainn** [comment]
Yes, change the icon files and go ahead and add the tooltip stuff. :)

**Comment by astraiophos** [comment]
Kay, I'm about finished, but I'm at a loss on how to use the commandline to generate a new css file. Any tips?
On Jul 21, 2016 12:53 PM, Nathan Swain <notifications@github.com> wrote:Yes, change the icon files and go ahead and add the tooltip stuff. :)

**Comment by swainn** [comment]
Take a look at the less.js documentation:

http://lesscss.org/#getting-started

You'll need to install node to install less:

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by astraiophos** [comment]
Thank you
On Jul 21, 2016 1:39 PM, Nathan Swain <notifications@github.com> wrote:Take a look at the less.js documentation:

http://lesscss.org/#getting-started

You'll need to install node to install less:

https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by astraiophos** [comment]
The dev branch pull request is up, should function properly

**Pull request closed without merging**
