### PR TITLE
Exception handling middleware (AJAX)

### PR DESCRIPTION
**Pull request by snowman2**

### CODE REVIEW

**Comment by snowman2** [comment]
Hi @sdc50, I have examples [here](https://github.com/erdc/tethysapp-streamflow_prediction_tool/blob/master/tethysapp/streamflow_prediction_tool/controllers_ajax.py). Just replace the local imports with the tethys imports.

**Comment by snowman2** [comment]
Also, for the JS side, [this](https://github.com/erdc/tethysapp-streamflow_prediction_tool/blob/master/tethysapp/streamflow_prediction_tool/public/js/main.js#L306-L332) is helpful.

**Comment by swainn** [comment]
@sdc50 and I recommend implementing this as an extension. If it gains wide adoption, then we could consider merging it into core.

**Comment by snowman2** [comment]
This is pretty old and likely outdated - and I completely forgot about it. I think closing it is appropriate.

**Comment by sdc50** [comment]
@snowman2 I'll take this one too (eventually).

**Comment by snowman2** [comment]
Sounds good 👍

**Pull request closed without merging**
