### PR TITLE
Geoserver Database Model

### PR DESCRIPTION
**Pull request by snowman2**

### CODE REVIEW

**Comment by swainn** [comment]
@sdc50 and I recommend implementing this as an extension. If it gains wide adoption, then we could consider merging it into core.

**Comment by snowman2** [comment]
This is pretty old and likely outdated - and I completely forgot about it. I think closing it is appropriate.

**Comment by sdc50** [comment]
@snowman2 I know that you are busy with other things (like completely rewriting pyproj 🥇), so we should have mentioned that I was planning to take on updating this PR and converting it into an extension. We like the idea, but just haven't gotten to working it in yet. I'm going to reopen to make sure I don't forget about it.

**Comment by snowman2** [comment]
Sounds good 👍

**Pull request closed without merging**
