### PR TITLE
Pywps tethys 2.0

### PR DESCRIPTION
**Pull request by xhqiao89**
This PR adds PyWPS integration to Tethys 2.0.
A brief user manual is here:
https://docs.google.com/document/d/1T69qH3EJUecvp6vXuk0S3NhMcq9A9n7kfeuFmw7eOYM/edit?usp=sharing
Thanks

### CODE REVIEW

**Comment by sdc50** [comment]
@swainn Did you see this demoed? Sherry was just asking about when we plan to merge it in. I'm happy to review it and merge, but I'm interested in your thoughts if you saw the demo.

**Comment by sdc50** [comment]
Sherry, I'm sorry we've taken so long to review this. I'm just beginning to review this now. I'm just going to test it out and then I'll merge soon or let you know if I have any questions.

**Comment by xhqiao89** [comment]
https://github.com/xhqiao89/pywps/tree/tethys_fix 

This is revised version of PyWPS used.

**Comment by swainn** [comment]
@xhqiao89: @sdc50 and I were reviewing Pull Requests today. We recommend implementing this as a Tethys Extension now that they have been released in Tethys 2.1. See: http://docs.tethysplatform.org/en/stable/tethys_sdk/extensions.html

**Comment by xhqiao89** [comment]
@swainn Thanks for the recommendation. I will be looking into it.

**Pull request closed without merging**
