### PR TITLE
Pin SQLAlchemy temporarily to fix failing tests + black update

### PR DESCRIPTION
**Pull request by swainn**
SQLAlchemy released version 2.0 and it appears to be causing some of our tests to fail (see: #918).

This PR:
-  pins SQLAlchemy to 1.*
-  formatting changes from the black 23.1.0 update.

### CODE REVIEW

**Comment by swainn** [comment]
@sdc50 this should fix the failing tests. I've also opened #918 to remind us to investigate what it would take to update to sqlalchemy 2.0.

**Comment by sdc50** [comment]
> @sdc50 this should fix the failing tests. I've also opened #918 to remind us to investigate what it would take to update to sqlalchemy 2.0.

Thanks! I didn't get back to this after sending out the election stuff.

**Review by sdc50 — APPROVED** [review]

**Comment by sdc50** [comment]
I guess Black decided it didn't like blank lines?

**Comment by swainn** [comment]
> I guess Black decided it didn't like blank lines?

I guess so. I'm not complaining. Haha.

**Pull request merged**
