### PR TITLE
Fix django-guardian version

### PR DESCRIPTION
**Pull request by rileyhales**
the fix suggested in response to Issue #480 and tested by myself and @rfun

### CODE REVIEW

**Comment by rileyhales** [comment]
Travis failed but if you check the details it had the same errors on the python 2 and 3 versions but only failed on 3. it also worked for me locally and apparently also for rohit. not sure whats up with that.

**Comment by swainn** [comment]
@rileyhales @rfun can you confirm if this issue is in the master branch? Do we need to merge this into that branch as well?

**Comment by rileyhales** [comment]
@swainn i just tried a fresh install of tethys 3.0.0 from the tethysplatform/label/dev channel using http://docs.tethysplatform.org/en/latest/installation.html instructions and it seems to be fine. i installed, generated settings, configured the db, and started a local server without any problems.

**Comment by swainn** [comment]
@sdc50 and @SarvaPulla the tests that are failing b/c of a change with the latest version of condorpy. I'm looking into that issue now, but it seems to be unrelated to these changes. I recommend we merge these changes and release a patch version, but I'd like at least one of you to take a look and double-check my reasoning.

**Comment by swainn** [comment]
> @swainn i just tried a fresh install of tethys 3.0.0 from the tethysplatform/label/dev channel using http://docs.tethysplatform.org/en/latest/installation.html instructions and it seems to be fine. i installed, generated settings, configured the db, and started a local server without any problems.

Thanks @rileyhales

**Comment by swainn** [comment]
Sorry this took so long.

**Pull request merged**
